# NOTE: This needs to be present in the namespace where Rollouts is to be executed
# This secret, nothing secret in this yet, contains configuration
# that is used by all Rollout Analysis operations 
#
# kubectl -n YOUR-ROLLOUT-NAMESPACE apply -f opsmx-profile.yaml # if creating manually..best to let ArgoCD sync it.

apiVersion: v1
kind: Secret
metadata:
  name: opsmx-profile                           # Default Name. No change necessary. It is referred in the AnalysisTemplate
stringData:
  opsmxIsdUrl: "https://ISD.REPLACE.THIS.WITH.YOURCOMPANY.COM"  # URL of ISD platform
  user: "admin"                                 # Default User. Change to an ISD platform User who has access to the data source (monitoring tools)
  sourceName: "argocd"                          # Argo CD name used in Setup->CDIntegration in ISD

  # Default is True.  Change to false if using Rollouts without Argo CD
  cdIntegration: "true"

