# Service Account+Role that allows the Rollouts Job check status of other pods
# Must be created in the namespace where Rollouts is being executed
#
# No change necessary. Use as is.
# kubectl -n YOUR-ROLLOUT-NAMESPACE apply -f opsmx-profile.yaml # if creating manually..best to let ArgoCD sync it.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opsmx-provider-account 
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opsmx-provider-account
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs/status
    verbs:
      - get
      - list
      - patch
  - apiGroups:	
      - ""	
    resources:	
      - pods	
    verbs:	
      - get	
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opsmx-provider-account
subjects:
  - kind: ServiceAccount
    name: opsmx-provider-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opsmx-provider-account
