apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: opsmx-newrel-tmpl                     ## This AnalysisTemplate is used in rollout.yaml
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: opsmx-newrel-tmpl                ## Match it with the above AnalysisTemplate name.
      initialDelay: 10s
      provider:
        job:
          spec:
            backoffLimit: 2
            template:
              spec:
                serviceAccountName: job-acc2         ## Match it with Service Account name
                containers:
                - name: opsmx-analysis
                  image: 'quay.io/opsmxpublic/argo-isd-metric-provider-job:v2'  
                  imagePullPolicy: Always
                  env:
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: STABLE_POD_HASH
                      value: "{{args.baseline-hash}}"
                    - name: LATEST_POD_HASH
                      value: "{{args.canary-hash}}"
                  volumeMounts:
                    - name: provider-config-volume
                      mountPath: /etc/config/provider
                    - name: verification-config-volume
                      mountPath: /etc/config/templates                      
                    - name: secret-config-volume
                      mountPath: /etc/config/secrets
                      readOnly: true
                restartPolicy: Never
                volumes:
                - name: provider-config-volume
                  configMap:
                    name: opsmx-provider-config           ## Match it with Analysis Configuration 
                - name: verification-config-volume
                  projected:
                    sources:
                    - configMap:
                        name: logtemplate                 ## Match it with the Log Template name
                    - configMap:
                        name: metrictemplate              ## Match it with the Metrics Template name
                - name: secret-config-volume
                  secret:
                    secretName: opsmx-profile             ## Match it with the Kubernetes Secret name 
                    optional: false
