apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: opsmx-analysis-template
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: opsmx-analysis-template
      initialDelay: 30s
      provider:
        job:
          spec:
            backoffLimit: 2
            template:
              spec:
                serviceAccountName: opsmx-provider-account
                containers:
                - name: canary-demo-analysis-job
                  image: quay.io/opsmxpublic/argo-isd-metric-provider-job:v1.2.1
                  imagePullPolicy: Always
                  env:
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: STABLE_POD_HASH
                      value: "{{args.baseline-hash}}"
                    - name: LATEST_POD_HASH
                      value: "{{args.canary-hash}}"
                  volumeMounts:
                    - name: provider-config-volume
                      mountPath: /etc/config/provider
                    - name: verification-templates-volume
                      mountPath: /etc/config/templates
                    - name: secret-config-volume
                      mountPath: /etc/config/secrets
                      readOnly: true
                restartPolicy: Never
                volumes:
                - name: provider-config-volume
                  configMap:
                    name: opsmx-provider-config
                - name: verification-templates-volume
                  projected:
                    sources:
                    - configMap:
                        name: prometheus-app-health-springboot-min
                    - configMap:
                        name: elasticsearch-generic-minimal
                - name: secret-config-volume
                  secret:
                    secretName: opsmx-profile
                    optional: false   
