
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    application: opsmx-demo
    lifetimeMinutes: 05
    gitops: true
    passScore: 60
    serviceList:
    - metricScopeVariables: "${app_key},${host_key}"
      baselineMetricScope: "opsmx-demo,{{env.STABLE_POD_HASH}}"
      canaryMetricScope: "opsmx-demo,{{env.LATEST_POD_HASH}}"
      metricTemplateName: "metrictemplate"
      logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      logTemplateName: "logtemplate"
