apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config                  ## Default Name.  Change if multiple analysis is needed in the same namespace
data:
  providerConfig: |
    application: opsmx-demo                    ## Change this to your application name as created in ArgoCD
    lifetimeMinutes: 05                        ## Change to Analysis Duration in minutes
    gitops: true
    passScore: 60                              ## Change to Minimum Pass Score.  Any score above this score will continue Rollout.
    serviceList:
    - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "opsmx-demo,.*{{env.STABLE_POD_HASH}}.*,opsmx-demo"
      canaryMetricScope: "opsmx-demo,.*{{env.LATEST_POD_HASH}}.*,opsmx-demo"
      metricTemplateName: "prometheus-app-health-springboot-min"
      logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: ".*{{env.STABLE_POD_HASH}}.*"
      canaryLogScope: ".*{{env.LATEST_POD_HASH}}.*"
      logTemplateName: "elasticsearch-generic-minimal"
